name: Checks

on: [push]

jobs:
  linters-checks:
    name: clang-format check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install -y clang-format
          clang-format --version
      - name: clang-format check
        run: |
          find src/ include/ tests/ -type f -name '(.*cpp|.*h)' \
          | xargs -n1 clang-format -Werror --dry-run

  send-telegram-message-on-failure:
    runs-on: ubuntu-22.04
    needs: linters-checks
    name: Send error message to telegram
    if: always() && (needs.linters-checks.result == 'failure')
    steps:
      - uses: kuznetsss/telegram_text_message_action@dev
        with:
          message: |
            <b>Github workflow failed</b>
            CI <a href=\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\">action</a> in <a href=\"${{ github.server_url }}/${{ github.repository }}\">${{ github.repository }}</a> failed.
          format: html
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
