name: Checks

on: [push, pull_request]

jobs:
  linters-checks:
    name: clang-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install -y clang-format
          clang-format --version
      - name: clang-format check
        run: |
          find src/ include/ tests/ -type f -name '(.*cpp|.*h)' \
          | xargs -n1 clang-format -Werror --dry-run
