name: Checks

on: [push]

jobs:
  clang-format_check:
    name: clang-format check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt install -y clang-format
          clang-format --version
      - name: clang-format check
        run: clang-format -Werror --dry-run `find include/ tests/ -type f -regex '\(.*cpp\|.*h\)'`

  build_and_clang-tidy_check:
    name: Build and run clang-tidy check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang and clang-tidy
        run: |
          sudo apt install -y clang clang-tidy
          clang-tidy --version
      - name: build
        run: |
          cmake -B build .
          cmake --build build -j2 
      - name: clang-tidy check
        run: clang-tidy `find include/ tests/ -type f -regex '\(.*cpp\|.*h\)'`

  send-telegram-message-on-failure:
    runs-on: ubuntu-22.04
    needs: [clang-format_check, build_and_clang-tidy_check]
    name: Send error message to telegram
    if: |
      always() && (
        needs.clang-format_check.result == 'failure'
        || needs.build_and_clang-tidy_check.result == 'failure'
      )
    steps:
      - uses: kuznetsss/telegram_text_message_action@dev
        with:
          message: |
            <b>Github workflow failed</b>
            CI <a href=\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\">action</a> in <a href=\"${{ github.server_url }}/${{ github.repository }}\">${{ github.repository }}</a> failed.
          format: html
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
